language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.2
branches:
  only:
  - master
  - develop

env:
  global:
  - SOURCERY_PROJECT="Sourcery/Sourcery.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="Sourcery"
  - IOS_SDK=iphonesimulator9.3
  matrix:
  - DESTINATION="OS=9.3,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --platform iOS

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$SOURCERY_PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build test | xcpretty;
    else
      xcodebuild -project "$SOURCERY_PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty;
    fi

  # Build in release
  - xcodebuild -project "$SOURCERY_PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean build | xcpretty;
